function octans = read_ocn(filename)
% DESCRIPTION: 
%
% USAGE:
%  
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%       
% AUTHOR: James Kinsey jkinsey@whoi.edu
%
% COPYRIGHT(c): James C. Kinsey 2002


% MODIFICATION HISTORY
% 2009-05-27 JCK - added DSL time struct
%

fprintf(1,'Reading Octans ascii data from from file %s \n', filename);


[   octans.string,...
    octans.date(:,1),...
    octans.date(:,2),...
    octans.date(:,3),...
    octans.time(:,1),...
    octans.time(:,2),...
    octans.time(:,3),...
    octans.codes(:,1),...
    octans.codes(:,2),...
    octans.position(:,1),...
    octans.position(:,2),...
    octans.position(:,3),...
    octans.position(:,4),...
    octans.position(:,5),...
    octans.position(:,6),...
    octans.velocity(:,1),...
    octans.velocity(:,2),...
    octans.velocity(:,3),...
    octans.velocity(:,4),...
    octans.velocity(:,5),...
    octans.velocity(:,6),...
    octans.accel(:,1),...
    octans.accel(:,2),...
    octans.accel(:,3),...
    octans.accel(:,4),...
    octans.accel(:,5),...
    octans.accel(:,6),...
    octans.position_time,...
    octans.velocity_time,...
    octans.accel_time,...
    octans.lat_cmd,...
    octans.lat_rpt,...
    octans.speed_cmd,...
    octans.speed_rpt,...
    octans.protocol,...
    octans.status,...
    octans.string_tstamp...
    octans.delta_t,...
    octans.parse_status,...
    octans.unix_time        ] = textread(filename,'%3s %f/%f/%f %f:%f:%f %4s %3s %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f');
    octans.unix_time = ymdhms_to_sec(octans.date(:,1), octans.date(:,2), octans.date(:,3),...
        octans.time(:,1), octans.time(:,2), octans.time(:,3));

    octans.gyro_attitude(:,1)      = unwrap360(octans.position(:,4));
    octans.gyro_attitude(:,2)      = unwrap360(octans.position(:,5));
    octans.gyro_attitude(:,3)      = unwrap360(octans.position(:,6));
    
    octans.gyro_attitude_rate(:,1:3) = octans.velocity(:,4:6);    

    octans.t = octans.unix_time; 
