function phins = read_phins(filename,orig_lat,orig_lon)

  
% first read the data from the phh_pos data file
  
  fprintf(1,'Reading Phins Position ascii data from from file %s \n', filename);

  [   phins.string,...
      phins.date(:,1),...
      phins.date(:,2),...
      phins.date(:,3),...
      phins.time(:,1),...
      phins.time(:,2),...
      phins.time(:,3),...
      phins.codes(:,1),...
      phins.codes(:,2),...
      phins.firmware_time,...
      phins.latitude,...
      phins.lat_sphere,...
      phins.longitude,...
      phins.lon_sphere,...
      phins.depth,...
      phins.altitude,...
      phins.lat_sigma,...
      phins.lon_sigma,...
      phins.lat_lon_covar,...
      phins.depth_sigma,...
      phins.utm_zone,...
      phins.utm_zone_char,...
      phins.east_proejection,...
      phins.north_projection,...
      phins.dvl_alignment,...
      phins.dvl_scale_factor,...
      phins.sound_speed          ] = textread(filename,'%3s %f/%f/%f %f:%f:%f %6s,%6s,%f,%f,%1s,%f,%1s,%f,%f,%f,%f,%f,%f,%f,%1s,%f,%f,%f,%f,%f');

  phins.unix_time = ymdhms_to_sec(phins.date(:,1), phins.date(:,2), phins.date(:,3),...
                                   phins.time(:,1), phins.time(:,2), phins.time(:,3));


  
  fname = strcat(filename,'_att');
    
  fprintf(1,'Reading Phins Attitude ascii data from from file %s \n', fname);


  [   phins.string,...
      phins.att_date(:,1),...
      phins.att_date(:,2),...
      phins.att_date(:,3),...
      phins.att_time(:,1),...
      phins.att_time(:,2),...
      phins.att_time(:,3),...
      phins.codes(:,3),...
      phins.codes(:,4),...
      phins.attitude(:,1),...
      phins.attitude(:,2),...
      phins.attitude(:,3),...
      phins.heave,...
      phins.attitude_rate(:,1),...
      phins.attitude_rate(:,2),...
      phins.attitude_rate(:,3),...
      phins.cog,...
      phins.sog,...
      phins.long_vel,...
      phins.trans_vel,...
      phins.vert_vel,...
      phins.attitude_sigma(:,1),...
      phins.attitude_sigma(:,2),...
      phins.attitude_sigma(:,3),...
      phins.north_velocity_sigma,...
      phins.east_velocity_sigma,...
      phins.vert_velocity_sigma         ] = textread(fname,'%3s %f/%f/%f %f:%f:%f %6s,%6s,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f');
  

  %the phins gives us latitude and longitude in degrees and decimal
  %minutes.  We want them in decimal degrees.
  
  lat_tmp = floor(phins.latitude/100);
  lat_tmp2 = ((phins.latitude/100 - lat_tmp)*100)/60 + lat_tmp;
  phins.latitude = lat_tmp2;
  
  lon_tmp = floor(phins.longitude/100);
  lon_tmp2 = ((phins.longitude/100 - lon_tmp)*100)/60 + lon_tmp;
  phins.longitude = lon_tmp2;

  if strcmp(phins.lat_sphere(1),'S')
    phins.latitude = -1.0 * phins.latitude;
  end
  
  if strcmp(phins.lon_sphere(1),'W')
    phins.longitude = -1.0 * phins.longitude;
  end
  
  %convert the lat/lon to local xy
  
  [x,y] = ll2xy(phins.latitude,phins.longitude,orig_lat,orig_lon);
  
  %create the position array
  phins.position(:,1) = x;
  phins.position(:,2) = y;
  phins.position(:,3) = -phins.depth;
  phins.position(:,4) = phins.attitude(:,1);
  phins.position(:,5) = phins.attitude(:,2);
  phins.position(:,6) = phins.attitude(:,3);
  
  phins.position_sigma(:,1) = phins.lat_sigma;
  phins.position_sigma(:,2) = phins.lon_sigma;
  phins.position_sigma(:,3) = phins.depth_sigma;
  phins.position_sigma(:,4) = phins.attitude_sigma(:,1);
  phins.position_sigma(:,5) = phins.attitude_sigma(:,2);
  phins.position_sigma(:,6) = phins.attitude_sigma(:,3);

  
  % these are poorly definded and will have to be sorted out
  phins.velocity(:,1) = phins.long_vel;
  phins.velocity(:,2) = phins.trans_vel;
  phins.velocity(:,3) = phins.vert_vel;
  
  phins.velocity_sigma(:,1) = phins.north_velocity_sigma;
  phins.velocity_sigma(:,2) = phins.east_velocity_sigma;
  phins.velocity_sigma(:,3) = phins.vert_velocity_sigma; 
